/** Programming-language identifiers used by claims and references. */
export type EvidenceProgrammingType =
  | "c"
  | "cpp"
  | "csharp"
  | "dart"
  | "go"
  | "java"
  | "javascript"
  | "kotlin"
  | "lua"
  | "matlab"
  | "objc"
  | "php"
  | "python"
  | "ruby"
  | "rust"
  | "scala"
  | "swift"
  | "typescript"
  | "zig";
