import type {} from "@ttsc/evidence";
import type { ITtscLintConfig } from "@ttsc/lint";

/**
 * Shared compile errors inherited by each project's lint.config.ts.
 *
 * Adapted from samchon/ttsc's Evid benchmark shared configuration, with
 * additional restrictions on any, assertions, unsafe values, and conditions.
 * Prettier owns formatting; every enabled lint rule fails the compiler.
 */
export default {
  rules: {
    "evidence/singular": "error",

    // Runtime correctness and unambiguous control flow.
    "default-param-last": "error",
    eqeqeq: "error",
    "for-direction": "error",
    "getter-return": "error",
    "guard-for-in": "error",
    "no-array-constructor": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-constant-condition": "error",
    "no-constructor-return": "error",
    "no-debugger": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "no-empty": "error",
    "no-empty-pattern": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-invalid-this": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-multi-assign": "error",
    "no-new-func": "error",
    "no-obj-calls": "error",
    "no-object-constructor": "error",
    "no-promise-executor-return": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-return-assign": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-this-before-super": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-useless-assignment": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-var": "error",
    "prefer-const": "error",
    radix: "error",
    "use-isnan": "error",
    "valid-typeof": "error",

    // Invalid or misleading regular expressions.
    "regexp/no-dupe-characters-character-class": "error",
    "regexp/no-empty-alternative": "error",
    "regexp/no-empty-capturing-group": "error",
    "regexp/no-empty-group": "error",
    "regexp/no-useless-escape": "error",
    "regexp/no-useless-flag": "error",
    "regexp/no-zero-quantifier": "error",

    // Promise chains must preserve failures and settle correctly.
    "promise/no-multiple-resolved": "error",
    "promise/no-new-statics": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/spec-only": "error",

    // Concrete unsafe APIs and misleading source text.
    "security/detect-bidi-characters": "error",
    "security/detect-buffer-noassert": "error",
    "security/detect-eval-with-expression": "error",
    "security/detect-new-buffer": "error",
    "security/detect-pseudoRandomBytes": "error",
    "security/detect-unsafe-regex": "error",

    // Type-aware checks also apply to tests, with no weaker preset.
    "typescript/adjacent-overload-signatures": "error",
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/no-array-delete": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/require-array-sort-compare": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/restrict-template-expressions": "error",
    "typescript/strict-boolean-expressions": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/unbound-method": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",

    // EvidNode API and runtime traps.
    "unicorn/error-message": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/prefer-node-protocol": "error",
  },
} satisfies ITtscLintConfig;
